### ISSUE TITLE
Convert to a gist

### ISSUE THREAD

**Issue by pulasthibandara** [pstephan1187/laravel-tools#1]
Just a suggestion, It seems this would wok particularly well as a gist :)

**Comment by pstephan1187** [comment]
I'm open to the idea. Why would it be better as a gist?

**Comment by pulasthibandara** [comment]
Well, It came to my mind when I tried to comment on the document about adding this laravel admin panel called voyager,
https://the-control-group.github.io/voyager/

If it was a Gist, it would have been easier to start a conversation. On the other hand for a conventional repo you may have to open an issue
